`include "../../DefaultParameters/defaultParametersPkg.sv"
import defaultParametersPkg::*;

module immediateGenerator(
    input  logic [31:0] instruction,   // INSTRUCTION
    output logic [31:0] immediateValue // GENERATED IMMEDIATE VALUE
);

    logic [6:0] opcode;
    assign opcode = instruction[6:0]; // OPCODE

    // ALL IMMEDIATE VALUES ARE GENERATED BY SIGN EXTENSION

    always_comb begin

        // DEFAULT
        immediateValue = 32'b0;

        case(opcode)

            // I-TYPE
            IType: begin
                immediateValue = {{20{instruction[31]}}, instruction[31:20]};
            end

            // S-TYPE
            SType: begin
                immediateValue = {{20{instruction[31]}}, instruction[31:25], instruction[11:7]};
            end

            // B-TYPE
            BType: begin
                immediateValue = {{19{instruction[31]}}, instruction[31], instruction[7], instruction[30:25], instruction[11:8], 1'b0};
            end

            // U-TYPE
            UType: begin
                immediateValue = {instruction[31:12], 12'b0};
            end

            // J-TYPE
            JType: begin
                immediateValue = {{11{instruction[31]}}, instruction[31], instruction[19:12], instruction[20], instruction[30:21], 1'b0};
            end

        endcase
    end

endmodule